#include "species_names.h"

#include <stddef.h>

static const char *const k_species[] = {
    "(none)",
    /*   1 */ "Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon",
    /*   6 */ "Charizard","Squirtle","Wartortle","Blastoise","Caterpie",
    /*  11 */ "Metapod","Butterfree","Weedle","Kakuna","Beedrill",
    /*  16 */ "Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate",
    /*  21 */ "Spearow","Fearow","Ekans","Arbok","Pikachu",
    /*  26 */ "Raichu","Sandshrew","Sandslash","Nidoran F","Nidorina",
    /*  31 */ "Nidoqueen","Nidoran M","Nidorino","Nidoking","Clefairy",
    /*  36 */ "Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff",
    /*  41 */ "Zubat","Golbat","Oddish","Gloom","Vileplume",
    /*  46 */ "Paras","Parasect","Venonat","Venomoth","Diglett",
    /*  51 */ "Dugtrio","Meowth","Persian","Psyduck","Golduck",
    /*  56 */ "Mankey","Primeape","Growlithe","Arcanine","Poliwag",
    /*  61 */ "Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam",
    /*  66 */ "Machop","Machoke","Machamp","Bellsprout","Weepinbell",
    /*  71 */ "Victreebel","Tentacool","Tentacruel","Geodude","Graveler",
    /*  76 */ "Golem","Ponyta","Rapidash","Slowpoke","Slowbro",
    /*  81 */ "Magnemite","Magneton","Farfetch'd","Doduo","Dodrio",
    /*  86 */ "Seel","Dewgong","Grimer","Muk","Shellder",
    /*  91 */ "Cloyster","Gastly","Haunter","Gengar","Onix",
    /*  96 */ "Drowzee","Hypno","Krabby","Kingler","Voltorb",
    /* 101 */ "Electrode","Exeggcute","Exeggutor","Cubone","Marowak",
    /* 106 */ "Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing",
    /* 111 */ "Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan",
    /* 116 */ "Horsea","Seadra","Goldeen","Seaking","Staryu",
    /* 121 */ "Starmie","Mr. Mime","Scyther","Jynx","Electabuzz",
    /* 126 */ "Magmar","Pinsir","Tauros","Magikarp","Gyarados",
    /* 131 */ "Lapras","Ditto","Eevee","Vaporeon","Jolteon",
    /* 136 */ "Flareon","Porygon","Omanyte","Omastar","Kabuto",
    /* 141 */ "Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos",
    /* 146 */ "Moltres","Dratini","Dragonair","Dragonite","Mewtwo",
    /* 151 */ "Mew",
    /* 152 */ "Chikorita","Bayleef","Meganium","Cyndaquil","Quilava",
    /* 157 */ "Typhlosion","Totodile","Croconaw","Feraligatr","Sentret",
    /* 162 */ "Furret","Hoothoot","Noctowl","Ledyba","Ledian",
    /* 167 */ "Spinarak","Ariados","Crobat","Chinchou","Lanturn",
    /* 172 */ "Pichu","Cleffa","Igglybuff","Togepi","Togetic",
    /* 177 */ "Natu","Xatu","Mareep","Flaaffy","Ampharos",
    /* 182 */ "Bellossom","Marill","Azumarill","Sudowoodo","Politoed",
    /* 187 */ "Hoppip","Skiploom","Jumpluff","Aipom","Sunkern",
    /* 192 */ "Sunflora","Yanma","Wooper","Quagsire","Espeon",
    /* 197 */ "Umbreon","Murkrow","Slowking","Misdreavus","Unown",
    /* 202 */ "Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce",
    /* 207 */ "Gligar","Steelix","Snubbull","Granbull","Qwilfish",
    /* 212 */ "Scizor","Shuckle","Heracross","Sneasel","Teddiursa",
    /* 217 */ "Ursaring","Slugma","Magcargo","Swinub","Piloswine",
    /* 222 */ "Corsola","Remoraid","Octillery","Delibird","Mantine",
    /* 227 */ "Skarmory","Houndour","Houndoom","Kingdra","Phanpy",
    /* 232 */ "Donphan","Porygon2","Stantler","Smeargle","Tyrogue",
    /* 237 */ "Hitmontop","Smoochum","Elekid","Magby","Miltank",
    /* 242 */ "Blissey","Raikou","Entei","Suicune","Larvitar",
    /* 247 */ "Pupitar","Tyranitar","Lugia","Ho-Oh","Celebi",
    /* 252 */ "Treecko","Grovyle","Sceptile","Torchic","Combusken",
    /* 257 */ "Blaziken","Mudkip","Marshtomp","Swampert","Poochyena",
    /* 262 */ "Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon",
    /* 267 */ "Beautifly","Cascoon","Dustox","Lotad","Lombre",
    /* 272 */ "Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow",
    /* 277 */ "Swellow","Wingull","Pelipper","Ralts","Kirlia",
    /* 282 */ "Gardevoir","Surskit","Masquerain","Shroomish","Breloom",
    /* 287 */ "Slakoth","Vigoroth","Slaking","Nincada","Ninjask",
    /* 292 */ "Shedinja","Whismur","Loudred","Exploud","Makuhita",
    /* 297 */ "Hariyama","Azurill","Nosepass","Skitty","Delcatty",
    /* 302 */ "Sableye","Mawile","Aron","Lairon","Aggron",
    /* 307 */ "Meditite","Medicham","Electrike","Manectric","Plusle",
    /* 312 */ "Minun","Volbeat","Illumise","Roselia","Gulpin",
    /* 317 */ "Swalot","Carvanha","Sharpedo","Wailmer","Wailord",
    /* 322 */ "Numel","Camerupt","Torkoal","Spoink","Grumpig",
    /* 327 */ "Spinda","Trapinch","Vibrava","Flygon","Cacnea",
    /* 332 */ "Cacturne","Swablu","Altaria","Zangoose","Seviper",
    /* 337 */ "Lunatone","Solrock","Barboach","Whiscash","Corphish",
    /* 342 */ "Crawdaunt","Baltoy","Claydol","Lileep","Cradily",
    /* 347 */ "Anorith","Armaldo","Feebas","Milotic","Castform",
    /* 352 */ "Kecleon","Shuppet","Banette","Duskull","Dusclops",
    /* 357 */ "Tropius","Chimecho","Absol","Wynaut","Snorunt",
    /* 362 */ "Glalie","Spheal","Sealeo","Walrein","Clamperl",
    /* 367 */ "Huntail","Gorebyss","Relicanth","Luvdisc","Bagon",
    /* 372 */ "Shelgon","Salamence","Beldum","Metang","Metagross",
    /* 377 */ "Regirock","Regice","Registeel","Latias","Latios",
    /* 382 */ "Kyogre","Groudon","Rayquaza","Jirachi","Deoxys",
    /* 387 */ "Turtwig","Grotle","Torterra","Chimchar","Monferno",
    /* 392 */ "Infernape","Piplup","Prinplup","Empoleon","Starly",
    /* 397 */ "Staravia","Staraptor","Bidoof","Bibarel","Kricketot",
    /* 402 */ "Kricketune","Shinx","Luxio","Luxray","Budew",
    /* 407 */ "Roserade","Cranidos","Rampardos","Shieldon","Bastiodon",
    /* 412 */ "Burmy","Wormadam","Mothim","Combee","Vespiquen",
    /* 417 */ "Pachirisu","Buizel","Floatzel","Cherubi","Cherrim",
    /* 422 */ "Shellos","Gastrodon","Ambipom","Drifloon","Drifblim",
    /* 427 */ "Buneary","Lopunny","Mismagius","Honchkrow","Glameow",
    /* 432 */ "Purugly","Chingling","Stunky","Skuntank","Bronzor",
    /* 437 */ "Bronzong","Bonsly","Mime Jr.","Happiny","Chatot",
    /* 442 */ "Spiritomb","Gible","Gabite","Garchomp","Munchlax",
    /* 447 */ "Riolu","Lucario","Hippopotas","Hippowdon","Skorupi",
    /* 452 */ "Drapion","Croagunk","Toxicroak","Carnivine","Finneon",
    /* 457 */ "Lumineon","Mantyke","Snover","Abomasnow","Weavile",
    /* 462 */ "Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire",
    /* 467 */ "Magmortar","Togekiss","Yanmega","Leafeon","Glaceon",
    /* 472 */ "Gliscor","Mamoswine","Porygon-Z","Gallade","Probopass",
    /* 477 */ "Dusknoir","Froslass","Rotom","Uxie","Mesprit",
    /* 482 */ "Azelf","Dialga","Palkia","Heatran","Regigigas",
    /* 487 */ "Giratina","Cresselia","Phione","Manaphy","Darkrai",
    /* 491 */ "Shaymin","Arceus",
    /* 493 */ "Arceus",
};

#define SPECIES_COUNT ((int)(sizeof(k_species) / sizeof(k_species[0])))

const char *species_name(uint16_t species) {
    if (species == 0 || species >= SPECIES_COUNT) return NULL;
    return k_species[species];
}
